### PR TITLE
More Sentences Traslated

### PR DESCRIPTION
**Pull request by pabgaran**
I am translating, but I don't have much time to do it. So, any help is welcome!

### CODE REVIEW

**Comment by PeterTheOne** [comment]
I updated the pad: https://titanpad.com/copywrongs-es . please remove "#"'s after translation!

**Comment by pabgaran** [comment]
Oh, you right. Sorry, is my way to view untranslated phrases quickly. I will be a commit in a while, with more translations and #'s removed.

**Comment by pabgaran** [comment]
@PeterTheOne  I will finish tomorrow. If you want merge now...

**Comment by PeterTheOne** [comment]
@pabgaran You can also check if you can use some new translations from: https://titanpad.com/copywrongs-es .. I will merge tommorow.

**Comment by PeterTheOne** [comment]
merged. when will you continue? ^^ please also check if you can use parts from: https://titanpad.com/copywrongs-es .

**Comment by PeterTheOne** [comment]
@pabgaran: this pad seems to be finished: https://titanpad.com/copywrongs-es

**Pull request merged**
