### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by crazygolem**
I am a native French speaker and based the translation on the English version.
It would not hurt to have someone proofread the translation before putting it in production (I am not a professional translator; "this translation is provided as-is" etc.) and check for overall consistency.

I chose to translate "copyright" as "droit d'auteur", which are slightly different concepts, as most European countries (especially all French speaking ones) uses the latter, not the former.
I was not able to translate "copywrong" while keeping the play on words, so I left it as is.

The link to the LQDN wiki (How to contact a MEP) is pointing to the English version, even if a French version is available. The link could not be modified from the translation file, which you might want to fix.

### CODE REVIEW

**Comment by PeterTheOne** [comment]
I merged it, but I guess it broke the build.. ^^ I will fix it now.

**Comment by PeterTheOne** [comment]
Fixed in 48836bdcb778e039b0328e8fb614505983904a08 . I hid the french lang menu option for now, feel free to review http://copywrongs.eu/fr/ and show the menu option again.

**Comment by PeterTheOne** [comment]
Please use https://yaml-online-parser.appspot.com/ to check for errors in the .yml file in the future. :)

**Comment by crazygolem** [comment]
Will do. Also a crash course in YAML might also be a good idea ^^'
I will review the french version tomorrow. I hope that letting a few hours pass before doing that will limit my bias enough.

**Comment by PeterTheOne** [comment]
The problem was the ":" in the text. I fixed it by putting the whole line in quotation marks like:

```
keykeykey: "bla bla: bla"
```

instead of 

```
keykeykey: bla bla: bla
```

**Comment by crazygolem** [comment]
I just reviewed my translation and I think that it is OK. The only think that I really wanted to change was the "I want it!" button, and @burnoutberni made a better translation for it. Thank you also @burnoutberni for the Reda's report links ;)

AFAIK, the only missing things are:
- Translations for the hover title of the amendments numbers (in `abbr` tags), but I don't have the courage to dig them up, and I don't even know if they exist in several languages;
- A way to configure in the language file the target of the "What will the call be like?" link, as there is a French version of the target page.

**Pull request merged**
