### PR TITLE
Adds Slovenian translation

### PR DESCRIPTION
**Pull request by Putr**
This adds the Slovenian translation.
# Important

Many of the fonts **do not support our common characters** - š, č, ž 

Czech and Croatian have the same problem!

End note: I did not edit any of the "call your rep" code - we intend to route a lot of Slovenians there, so this may be something to extend.

### CODE REVIEW

**Comment by PeterTheOne** [comment]
Thanks. Take a look: http://copywrongs.eu/sl/ . Also I fixed the language menu in 83ca7389c9c3a3e6308a54a8f196ea21fc41a2b4 .

**Comment by Putr** [comment]
Thanks you!

**Comment by PeterTheOne** [comment]
@Putr: Also please update your translation of these lines if you can: 9112b227530d01d130cf1ab7def8ca551fc7ac4e

**Comment by PeterTheOne** [comment]
#27

**Pull request merged**
