### PR TITLE
added spaces, based on review of the preview web

### PR DESCRIPTION
**Pull request by Aktron**

### CODE REVIEW

**Comment by Aktron** [comment]
now it should be OK to be published

**Comment by Aktron** [comment]
All right. The final version is ok. For some reasion it shows "Spasite copyright reform" in the title, despite the fact it should show "Spasite reformu autorskog prava". Everything is fine in the source document. Since we have only 7 days till voting and we would like to maximize the whole issue, I would recommend publishing this asap (with the language menu). Otherwise we are loosing time. 

The label for the language should be: "HR - hrvatski" but I believe this is already done with the file in the "hr" folder.

**Comment by PeterTheOne** [comment]
HR menu point is added already. :)

**Comment by PeterTheOne** [comment]
@Aktron: I found the error: you need to translate "savecreform" correctly.

**Comment by PeterTheOne** [comment]
I tried to fix it: fb61a48ab2e720f5cdbcbe2c5aa6064e96c817e9 .

**Pull request merged**
